# Generated by Django 3.0.8 on 2021-01-27 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='зображення')),
                ('description', models.TextField(null=True, verbose_name='опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='цiна')),
                ('diagonal', models.CharField(max_length=255, verbose_name='диагонал')),
                ('display_type', models.CharField(max_length=255, verbose_name='итп дисплея')),
                ('resolution', models.CharField(max_length=255, verbose_name='разрешение екрана')),
                ('accum_volume', models.CharField(max_length=255, verbose_name=' обьем батареі')),
                ('ram', models.CharField(max_length=255, verbose_name='оперативная память')),
                ('video', models.CharField(max_length=255, verbose_name='видео карта')),
                ('sd', models.BooleanField(default=True)),
                ('sd_volume_max', models.CharField(max_length=255, verbose_name='максимальная встраиваемая память')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='главная касера')),
                ('front_cam_mp', models.CharField(max_length=255, verbose_name='фронтальная камера')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='категорii')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='зображення')),
                ('description', models.TextField(null=True, verbose_name='опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='цiна')),
                ('diagonal', models.CharField(max_length=255, verbose_name='диагонал')),
                ('display_type', models.CharField(max_length=255, verbose_name='итп дисплея')),
                ('processor_freg', models.CharField(max_length=255, verbose_name='процесор')),
                ('ram', models.CharField(max_length=255, verbose_name='оперативная память')),
                ('video', models.CharField(max_length=255, verbose_name='видео карта')),
                ('time_without_charge', models.CharField(max_length=255, verbose_name='акумулятор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='категорii')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
