# Generated by Django 3.0.8 on 2021-02-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_productfeatures_productfeaturesvalidators'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfeatures',
            options={'verbose_name': 'Модель розширення продуктів2', 'verbose_name_plural': 'Модель розширення продуктів'},
        ),
        migrations.AlterModelOptions(
            name='productfeaturesvalidators',
            options={'verbose_name': 'Модель розширення продуктів + валідатор2', 'verbose_name_plural': 'Модель розширення продуктів + валідатор'},
        ),
        migrations.AlterField(
            model_name='productfeatures',
            name='filter_measure',
            field=models.CharField(help_text='Одиниця виміру для конкретного фільтру.Наприклад "Частота процесора (Ghz)"', max_length=50, verbose_name='Одиниця виміру для фільтра'),
        ),
    ]
